In [6]:
seq1 = "AAATGCGCAATCGA"
seq2 = "AATGATGCAGAGT"

In [11]:
import numpy as np
gap_penalty = -1


match_score = np.zeros((4, 4))
match_score[0][0] = 5
match_score[0][1] = match_score[1][0] = -2
match_score[0][2] = match_score[2][0] = -1
match_score[0][3] = match_score[3][0] = -1
match_score[1][1] = 7
match_score[1][2] = match_score[2][1] = -1
match_score[1][3] = match_score[3][1] = 3
match_score[2][2] = 7
match_score[2][3] = match_score[3][2] = 0
match_score[3][3] = 6
print(match_score)
letters = {"A" : 0, "T" : 1, "C" : 2, "G" : 3}

[[ 5. -2. -1. -1.]
 [-2.  7. -1.  3.]
 [-1. -1.  7.  0.]
 [-1.  3.  0.  6.]]


In [12]:
def needleman_wunsch(seqA, seqB):
    n = len(seqA)  
    m = len(seqB)

    score = np.zeros((m+1, n+1))

    for i in range(0, m + 1):
        score[i][0] = gap_penalty * i

    for j in range(0, n + 1):
        score[0][j] = gap_penalty * j
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            match = score[i - 1][j - 1] + match_score[letters[seq1[j-1]]][letters[seq2[i-1]]]
            delete = score[i - 1][j] + gap_penalty
            insert = score[i][j - 1] + gap_penalty
            score[i][j] = max(match, delete, insert)

    AlignmentA = ""
    AlignmentB = ""

    i = m
    j = n

    while i > 0 and j > 0:
        score_current = score[i][j]
        score_diagonal = score[i-1][j-1]
        score_up = score[i][j-1]
        score_left = score[i-1][j]

        if score_current == score_diagonal + match_score[letters[seq1[j-1]]][letters[seq2[i-1]]]:
            AlignmentA += seqA[j-1]
            AlignmentB += seqB[i-1]
            i -= 1
            j -= 1
        elif score_current == score_up + gap_penalty:
            AlignmentA += seqA[j-1]
            AlignmentB += '_'
            j -= 1
        elif score_current == score_left + gap_penalty:
            AlignmentA += '_'
            AlignmentB += seqB[i-1]
            i -= 1

    while j > 0:
        AlignmentA += seqA[j-1]
        AlignmentB += '_'
        j -= 1
    while i > 0:
        AlignmentA += '_'
        AlignmentB += seqB[i-1]
        i -= 1
    
    AlignmentA = AlignmentA[::-1]
    AlignmentB = AlignmentB[::-1]
    
    return(AlignmentA, AlignmentB)

output1, output2 = needleman_wunsch(seq1, seq2)

print(output1 + "\n" + output2)

AAATG_CGCA_ATCGA
_AATGATGCAGAG_T_


In [13]:
match_score[0][0] = 1
output1, output2 = needleman_wunsch(seq1, seq2)

print(output1 + "\n" + output2)

AAATG_CGCAATCGA
_AATGATGC_AGAGT
